FROM node:20-bookworm-slim AS deps

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./frontend/
RUN npm ci --prefix frontend

FROM node:20-bookworm-slim AS builder

WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_API_BASE_URL=http://localhost:3001
ARG NEXT_PUBLIC_AI_INTERVIEWER_SESSION_MODE=tts-file
ARG NEXT_PUBLIC_AI_INTERVIEWER_REALTIME_ENABLED=false
ARG NEXT_PUBLIC_AI_INTERVIEWER_AVATAR_STREAM_ENABLED=false
ARG NEXT_PUBLIC_OPENAI_REALTIME_STT_RELAY_ENABLED=true
ARG NEXT_PUBLIC_TOSS_CLIENT_KEY=""
ARG NEXT_PUBLIC_KAKAO_MAP_KEY=""
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_AI_INTERVIEWER_SESSION_MODE=$NEXT_PUBLIC_AI_INTERVIEWER_SESSION_MODE
ENV NEXT_PUBLIC_AI_INTERVIEWER_REALTIME_ENABLED=$NEXT_PUBLIC_AI_INTERVIEWER_REALTIME_ENABLED
ENV NEXT_PUBLIC_AI_INTERVIEWER_AVATAR_STREAM_ENABLED=$NEXT_PUBLIC_AI_INTERVIEWER_AVATAR_STREAM_ENABLED
ENV NEXT_PUBLIC_OPENAI_REALTIME_STT_RELAY_ENABLED=$NEXT_PUBLIC_OPENAI_REALTIME_STT_RELAY_ENABLED
ENV NEXT_PUBLIC_TOSS_CLIENT_KEY=$NEXT_PUBLIC_TOSS_CLIENT_KEY
ENV NEXT_PUBLIC_KAKAO_MAP_KEY=$NEXT_PUBLIC_KAKAO_MAP_KEY

COPY --from=deps /app/frontend/node_modules ./frontend/node_modules
COPY frontend ./frontend
RUN npm run build --prefix frontend

FROM node:20-bookworm-slim AS runner

WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

COPY --from=builder /app/frontend/.next/standalone ./
COPY --from=builder /app/frontend/.next/static ./.next/static
COPY --from=builder /app/frontend/public ./public

EXPOSE 3000
CMD ["node", "server.js"]
